#!/usr/bin/env python3
"""Render editor's marks as red ink on a copy of a draft.

    redline.py SOURCE EDITS.json [--out PATH] [--no-compile]

EDITS.json is a list of objects:
    {"old": "text copied verbatim from SOURCE", "new": "replacement", "note": "why"}
"new" and "note" are each optional. Without "new" the mark is a margin note
anchored at "old"; without "note" it is a bare strike/insert.

For .typ sources the output is SOURCE.redline.typ next to the original (so
imports and --root still resolve) and, unless --no-compile, a PDF beside it.
For anything else the output is an HTML redline.

Matching is whitespace-insensitive, so "old" may be copied from hard-wrapped
source as a single line. Each "old" must match exactly once; misses and
ambiguities are reported and skipped, never guessed.
"""
import argparse, difflib, html, json, re, shutil, subprocess, sys
from pathlib import Path

TYPST_PREAMBLE = """
// ---- redline marks (generated by line-edit/redline.py) ----
#let _rl-ink = rgb("#c0392b")
#let _rl-del(b) = text(fill: _rl-ink, strike(stroke: 0.6pt + _rl-ink, b))
#let _rl-ins(b) = text(fill: _rl-ink, b)
#let _rl-tag(n) = text(fill: _rl-ink, size: 0.7em, baseline: -0.45em, weight: "bold", str(n))
#let _rl-note(n, b) = %(NOTE)s
#let _rl-crib-ink = rgb("#6a3d9a")
#let _rl-crib(s, v, b) = text(fill: _rl-crib-ink, size: 0.85em)[
  #h(0.4em)#box(inset: (x: 2.5pt, y: 1pt), outset: (y: 1.5pt), stroke: 0.5pt + _rl-crib-ink, radius: 2pt,
    text(weight: "bold", font: ("Fira Sans", "Noto Sans"), size: 0.85em, s))
  #text(weight: "semibold", font: ("Fira Sans", "Noto Sans"), size: 0.85em, v)#if b != [] [ #emph(b)]]
// ----------------------------------------------------------
"""
NOTE_MARGIN = 'marginnote(text(fill: _rl-ink, size: 7.5pt, style: "italic")[#text(weight: "bold")[#str(n)] #b])'
NOTE_FALLBACK = 'footnote(text(fill: _rl-ink, style: "italic")[#str(n). #b])'


def pattern_for(old: str) -> re.Pattern:
    parts = [re.escape(p) for p in old.split()]
    return re.compile(r"\s+".join(parts))


def locate(text: str, old: str):
    ms = list(pattern_for(old).finditer(text))
    return ms


def apply_edits(text: str, edits, mark):
    """Return (new_text, report). `mark(n, matched, edit)` renders one mark."""
    # Locate everything against the original text first, then splice from the
    # end so earlier offsets stay valid. Overlapping edits are rejected.
    located, report = [], []
    for n, e in enumerate(edits, 1):
        old = e.get("old", "")
        if not old.strip():
            report.append(f"[{n}] skipped: empty 'old'"); continue
        ms = locate(text, old)
        if len(ms) == 0:
            report.append(f"[{n}] NOT FOUND: {old[:70]!r}"); continue
        if len(ms) > 1:
            report.append(f"[{n}] AMBIGUOUS ({len(ms)} matches), add context: {old[:70]!r}"); continue
        located.append((ms[0].start(), ms[0].end(), n, e))
    located.sort()
    for (a, b, n, _), (c, d, m, _) in zip(located, located[1:]):
        if c < b:
            report.append(f"[{n}] and [{m}] overlap; dropping [{m}]")
    kept, last_end = [], -1
    for a, b, n, e in located:
        if a < last_end:
            continue
        kept.append((a, b, n, e)); last_end = b
    out = text
    for a, b, n, e in reversed(kept):
        out = out[:a] + mark(n, text[a:b], e) + out[b:]
    report.append(f"applied {len(kept)} of {len(edits)} marks")
    return out, report


def word_diff(old: str, new: str):
    """Yield (kind, text) runs: 'eq', 'del', 'ins'. Word-level, so only the
    words that change are marked. Kept runs of a single word between two
    changes are folded into the change so the marks read as one stroke."""
    a, b = old.split(), new.split()
    sm = difflib.SequenceMatcher(a=a, b=b, autojunk=False)
    ops = [op for op in sm.get_opcodes()]
    # fold 1-word 'equal' islands between changes
    folded, i = [], 0
    while i < len(ops):
        tag, i1, i2, j1, j2 = ops[i]
        if tag == "equal" and i2 - i1 == 1 and 0 < i < len(ops) - 1:
            folded.append(("replace", i1, i2, j1, j2))
        else:
            folded.append(ops[i])
        i += 1
    # merge adjacent non-equal ops into single del/ins spans
    runs = []
    for tag, i1, i2, j1, j2 in folded:
        if tag == "equal":
            runs.append(("eq", " ".join(a[i1:i2])))
        else:
            d, ins = " ".join(a[i1:i2]), " ".join(b[j1:j2])
            if runs and runs[-1][0] == "chg":
                pd, pi = runs[-1][1], runs[-1][2]
                runs[-1] = ("chg", (pd + " " + d).strip(), (pi + " " + ins).strip())
            else:
                runs.append(("chg", d, ins))
    return runs


def esc(t: str) -> str:
    return t.replace("\\", "\\\\").replace("#", "\\#").replace("$", "\\$").replace("@", "\\@")


def typst_mark(n, matched, e):
    new, note = e.get("new"), e.get("note")
    if "score" in e:
        # CRIBS: paragraph verdict, appended to the paragraph's last sentence.
        v = e.get("verdict", "")
        return f'{matched}#_rl-crib("{esc(e["score"])}", "{esc(v)}")[{esc(note or "")}]'
    s = ""
    if new is not None:
        parts = []
        for run in word_diff(matched, new):
            if run[0] == "eq":
                parts.append(run[1])
            else:
                d, ins = run[1], run[2]
                piece = ""
                if d:
                    piece += f"#_rl-del[{d}]"
                if ins:
                    piece += (" " if d else "") + f"#_rl-ins[{ins}]"
                parts.append(piece)
        s += " ".join(parts)
    else:
        s += matched
    s += f"#_rl-tag({n})"
    if note:
        # notes are prose, not markup: neutralise typst specials
        s += f"#_rl-note({n})[{esc(note)}]"
    return s


def html_mark(n, matched, e):
    new, note = e.get("new"), e.get("note")
    if "score" in e:
        return (f"{html.escape(matched)}<span class=crib><b>{html.escape(e['score'])}</b> "
                f"{html.escape(e.get('verdict',''))} <i>{html.escape(note or '')}</i></span>")
    s = ""
    if new is not None:
        parts = []
        for run in word_diff(matched, new):
            if run[0] == "eq":
                parts.append(html.escape(run[1]))
            else:
                d, ins = run[1], run[2]
                parts.append((f"<del>{html.escape(d)}</del>" if d else "")
                             + (f"<ins>{html.escape(ins)}</ins>" if ins else ""))
        s += " ".join(parts)
    else:
        s += f"<mark>{html.escape(matched)}</mark>"
    s += f"<sup>{n}</sup>"
    if note:
        s += f"<aside><b>{n}</b> {html.escape(note)}</aside>"
    return s


HTML_SHELL = """<!doctype html><meta charset=utf-8><title>redline: %(name)s</title>
<style>
body{max-width:46rem;margin:3rem auto 3rem 6rem;font:16px/1.55 Georgia,serif;color:#222;background:#fbfaf7}
pre{white-space:pre-wrap;font:inherit;position:relative}
del{color:#c0392b;text-decoration:line-through}
ins{color:#c0392b;text-decoration:none;font-weight:600}
mark{background:none;border-bottom:1px dotted #c0392b}
sup{color:#c0392b;font-size:.7em;font-weight:bold}
.crib{color:#6a3d9a;font-size:.85em;margin-left:.4em}
aside{position:absolute;right:-17rem;width:15rem;font:italic 13px/1.35 Georgia,serif;color:#c0392b;margin-top:-1.4em}
@media(max-width:70rem){aside{position:static;display:block;width:auto;margin:.2em 0 .6em 1.5em}}
</style>
<pre>%(body)s</pre>
"""


def inject_typst_preamble(text: str, source: Path) -> str:
    # Use the template's marginnote if the imported template defines one.
    note = NOTE_FALLBACK
    m = re.search(r'^#import\s+"([^"]+)"', text, re.M)
    if m:
        tpl = (source.parent / m.group(1))
        if tpl.exists() and re.search(r"^#let marginnote\(", tpl.read_text(), re.M):
            note = NOTE_MARGIN
    pre = TYPST_PREAMBLE % {"NOTE": note}
    if m:  # after the import line
        end = text.index("\n", m.end()) + 1
        return text[:end] + pre + text[end:]
    return pre + text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source", type=Path)
    ap.add_argument("edits", type=Path)
    ap.add_argument("--out", type=Path)
    ap.add_argument("--no-compile", action="store_true")
    ap.add_argument("--root", type=Path, help="typst --root (default: the source file's directory)")
    ap.add_argument("--input", action="append", default=None, metavar="KEY=VAL",
                    help="typst --input, repeatable (default: booklet=1; templates that ignore it are unaffected)")
    ap.add_argument("--letter", action="store_true", help="drop the default booklet=1 input")
    a = ap.parse_args()

    text = a.source.read_text()
    edits = json.loads(a.edits.read_text())
    is_typst = a.source.suffix == ".typ"

    if is_typst:
        body, report = apply_edits(text, edits, typst_mark)
        # Escape nothing: marks are typst markup and 'old' is copied from source.
        out = a.out or a.source.with_suffix(".redline.typ")
        out.write_text(inject_typst_preamble(body, a.source))
    else:
        body, report = apply_edits(html.escape(text), [dict(e, old=html.escape(e["old"])) for e in edits],
                                   lambda n, m, e: html_mark(n, html.unescape(m), e))
        out = a.out or a.source.with_suffix(a.source.suffix + ".redline.html")
        out.write_text(HTML_SHELL % {"name": a.source.name, "body": body})

    print("\n".join(report))
    print(f"wrote {out}")

    if is_typst and not a.no_compile and shutil.which("typst"):
        root = a.root or a.source.resolve().parent
        pdf = out.with_suffix(".pdf")
        inputs = a.input if a.input is not None else ([] if a.letter else ["booklet=1"])
        cmd = ["typst", "compile", "--root", str(root)]
        for kv in inputs:
            cmd += ["--input", kv]
        r = subprocess.run(cmd + [str(out), str(pdf)], capture_output=True, text=True)
        if r.returncode == 0:
            print(f"compiled {pdf}")
        else:
            print("typst compile failed:\n" + r.stderr, file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
